version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:5.0
    container_name: study-buddy-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: study-buddy-matcher
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - study-buddy-network

  # Backend Service
  backend:
    build: ./backend
    container_name: study-buddy-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5002
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/study-buddy-matcher?authSource=admin
      JWT_SECRET: super_secret_jwt_key_change_in_production
      JWT_EXPIRE: 7d
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    networks:
      - study-buddy-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: study-buddy-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      VITE_API_URL: http://backend:5002/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - study-buddy-network

networks:
  study-buddy-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
